//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 10/21/2014 11:04:20 PM
namespace CumulusScheduler.Utilities
{
    
    /// <summary>
    /// There are no comments for Utilities in the schema.
    /// </summary>
    public partial class Utilities : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new Utilities object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Utilities(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "LightSwitchApplication.Models", "CumulusScheduler.Utilities");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("CumulusScheduler.Utilities", global::System.StringComparison.Ordinal))
            {
                return string.Concat("LightSwitchApplication.Models.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for HealthChecks in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<HealthCheck> HealthChecks
        {
            get
            {
                if ((this._HealthChecks == null))
                {
                    this._HealthChecks = base.CreateQuery<HealthCheck>("HealthChecks");
                }
                return this._HealthChecks;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<HealthCheck> _HealthChecks;
        /// <summary>
        /// There are no comments for ManagementCredentialHelpers in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<ManagementCredentialHelper> ManagementCredentialHelpers
        {
            get
            {
                if ((this._ManagementCredentialHelpers == null))
                {
                    this._ManagementCredentialHelpers = base.CreateQuery<ManagementCredentialHelper>("ManagementCredentialHelpers");
                }
                return this._ManagementCredentialHelpers;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<ManagementCredentialHelper> _ManagementCredentialHelpers;
        /// <summary>
        /// There are no comments for DispatchHelpers in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<DispatchHelper> DispatchHelpers
        {
            get
            {
                if ((this._DispatchHelpers == null))
                {
                    this._DispatchHelpers = base.CreateQuery<DispatchHelper>("DispatchHelpers");
                }
                return this._DispatchHelpers;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<DispatchHelper> _DispatchHelpers;
        /// <summary>
        /// There are no comments for HealthChecks in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToHealthChecks(HealthCheck healthCheck)
        {
            base.AddObject("HealthChecks", healthCheck);
        }
        /// <summary>
        /// There are no comments for ManagementCredentialHelpers in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToManagementCredentialHelpers(ManagementCredentialHelper managementCredentialHelper)
        {
            base.AddObject("ManagementCredentialHelpers", managementCredentialHelper);
        }
        /// <summary>
        /// There are no comments for DispatchHelpers in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToDispatchHelpers(DispatchHelper dispatchHelper)
        {
            base.AddObject("DispatchHelpers", dispatchHelper);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart0 = "<edmx:Edmx Version=\"1.0\" xmlns:edmx=\"http://schemas.microsoft.com/ado/2007/06/edm" +
                "x\"><edmx:DataServices m:DataServiceVersion=\"3.0\" m:MaxDataServiceVersion=\"3.0\" x" +
                "mlns:m=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\"><Schema " +
                "Namespace=\"LightSwitchApplication.Models\" xmlns=\"http://schemas.microsoft.com/ad" +
                "o/2009/11/edm\"><EntityType Name=\"HealthCheck\"><Key><PropertyRef Name=\"Id\" /></Ke" +
                "y><Property Name=\"Id\" Type=\"Edm.String\" Nullable=\"false\" /><Property Name=\"Descr" +
                "iption\" Type=\"Edm.String\" /><Property Name=\"TimeStamp\" Type=\"Edm.DateTimeOffset\"" +
                " /><Property Name=\"Status\" Type=\"Edm.String\" Nullable=\"false\" /><Property Name=\"" +
                "Active\" Type=\"Edm.Boolean\" Nullable=\"false\" /></EntityType><EntityType Name=\"Man" +
                "agementCredentialHelper\"><Key><PropertyRef Name=\"Id\" /></Key><Property Name=\"Id\"" +
                " Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"Name\" Type=\"Edm.String\" /><" +
                "Property Name=\"Description\" Type=\"Edm.String\" /><Property Name=\"Username\" Type=\"" +
                "Edm.String\" /><Property Name=\"Password\" Type=\"Edm.String\" /><Property Name=\"Crea" +
                "ted\" Type=\"Edm.DateTime\" Nullable=\"false\" /><Property Name=\"CreatedBy\" Type=\"Edm" +
                ".String\" /><Property Name=\"Modified\" Type=\"Edm.DateTime\" Nullable=\"false\" /><Pro" +
                "perty Name=\"ModifiedBy\" Type=\"Edm.String\" /></EntityType><EntityType Name=\"Dispa" +
                "tchHelper\"><Key><PropertyRef Name=\"Id\" /></Key><Property Name=\"Id\" Type=\"Edm.Int" +
                "32\" Nullable=\"false\" /><Property Name=\"Status\" Type=\"Edm.String\" /><Property Nam" +
                "e=\"Entity\" Type=\"Edm.String\" Nullable=\"false\" /><Property Name=\"EntitySet\" Type=" +
                "\"Edm.String\" Nullable=\"false\" /><Property Name=\"Uri\" Type=\"Edm.String\" Nullable=" +
                "\"false\" /><Property Name=\"LockName\" Type=\"Edm.String\" /><Property Name=\"ErrorId\"" +
                " Type=\"Edm.String\" /><Property Name=\"ErrorMessage\" Type=\"Edm.String\" /></EntityT" +
                "ype></Schema><Schema Namespace=\"Default\" xmlns=\"http://schemas.microsoft.com/ado" +
                "/2009/11/edm\"><EntityContainer Name=\"Utilities\" m:IsDefaultEntityContainer=\"true" +
                "\"><EntitySet Name=\"HealthChecks\" EntityType=\"LightSwitchApplication.Models.Healt" +
                "hCheck\" /><EntitySet Name=\"ManagementCredentialHelpers\" EntityType=\"LightSwitchA" +
                "pplication.Models.ManagementCredentialHelper\" /><EntitySet Name=\"DispatchHelpers" +
                "\" EntityType=\"LightSwitchApplication.Models.DispatchHelper\" /><FunctionImport Na" +
                "me=\"Acquire\" ReturnType=\"LightSwitchApplication.Models.DispatchHelper\" IsBindabl" +
                "e=\"true\" EntitySet=\"DispatchHelpers\" m:IsAlwaysBindable=\"true\"><Parameter Name=\"" +
                "bindingParameter\" Type=\"Collection(LightSwitchApplication.Models.DispatchHelper)" +
                "\" Nullable=\"false\" /><Parameter Name=\"Id\" Type=\"Edm.Int32\" Nullable=\"false\" /><P" +
                "arameter Name=\"Entity\" Type=\"Edm.String\" FixedLength=\"false\" Unicode=\"false\" /><" +
                "Parameter Name=\"EntitySet\" Type=\"Edm.String\" FixedLength=\"false\" Unicode=\"false\"" +
                " /><Parameter Name=\"Requester\" Type=\"Edm.String\" FixedLength=\"false\" Unicode=\"fa" +
                "lse\" /></FunctionImport><FunctionImport Name=\"Release\" ReturnType=\"LightSwitchAp" +
                "plication.Models.DispatchHelper\" IsBindable=\"true\" EntitySet=\"DispatchHelpers\" m" +
                ":IsAlwaysBindable=\"true\"><Parameter Name=\"bindingParameter\" Type=\"Collection(Lig" +
                "htSwitchApplication.Models.DispatchHelper)\" Nullable=\"false\" /><Parameter Name=\"" +
                "Id\" Type=\"Edm.Int32\" Nullable=\"false\" /><Parameter Name=\"Entity\" Type=\"Edm.Strin" +
                "g\" FixedLength=\"false\" Unicode=\"false\" /><Parameter Name=\"EntitySet\" Type=\"Edm.S" +
                "tring\" FixedLength=\"false\" Unicode=\"false\" /><Parameter Name=\"Requester\" Type=\"E" +
                "dm.String\" FixedLength=\"false\" Unicode=\"false\" /><Parameter Name=\"Status\" Type=\"" +
                "Edm.String\" FixedLength=\"false\" Unicode=\"false\" /></FunctionImport></EntityConta" +
                "iner></Schema></edmx:DataServices></edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static string GetConcatenatedEdmxString()
            {
                return string.Concat(ModelPart0);
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            public static global::Microsoft.Data.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel LoadModelFromString()
            {
                string edmxToParse = GetConcatenatedEdmxString();
                global::System.Xml.XmlReader reader = CreateXmlReader(edmxToParse);
                try
                {
                    return global::Microsoft.Data.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// There are no comments for LightSwitchApplication.Models.HealthCheck in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("HealthChecks")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class HealthCheck : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new HealthCheck object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="status">Initial value of Status.</param>
        /// <param name="active">Initial value of Active.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static HealthCheck CreateHealthCheck(string ID, string status, bool active)
        {
            HealthCheck healthCheck = new HealthCheck();
            healthCheck.Id = ID;
            healthCheck.Status = status;
            healthCheck.Active = active;
            return healthCheck;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Id;
        partial void OnIdChanging(string value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property TimeStamp in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTimeOffset> TimeStamp
        {
            get
            {
                return this._TimeStamp;
            }
            set
            {
                this.OnTimeStampChanging(value);
                this._TimeStamp = value;
                this.OnTimeStampChanged();
                this.OnPropertyChanged("TimeStamp");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _TimeStamp;
        partial void OnTimeStampChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnTimeStampChanged();
        /// <summary>
        /// There are no comments for Property Status in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Status
        {
            get
            {
                return this._Status;
            }
            set
            {
                this.OnStatusChanging(value);
                this._Status = value;
                this.OnStatusChanged();
                this.OnPropertyChanged("Status");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Status;
        partial void OnStatusChanging(string value);
        partial void OnStatusChanged();
        /// <summary>
        /// There are no comments for Property Active in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool Active
        {
            get
            {
                return this._Active;
            }
            set
            {
                this.OnActiveChanging(value);
                this._Active = value;
                this.OnActiveChanged();
                this.OnPropertyChanged("Active");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _Active;
        partial void OnActiveChanging(bool value);
        partial void OnActiveChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for LightSwitchApplication.Models.ManagementCredentialHelper in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("ManagementCredentialHelpers")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class ManagementCredentialHelper : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new ManagementCredentialHelper object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="created">Initial value of Created.</param>
        /// <param name="modified">Initial value of Modified.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static ManagementCredentialHelper CreateManagementCredentialHelper(int ID, global::System.DateTime created, global::System.DateTime modified)
        {
            ManagementCredentialHelper managementCredentialHelper = new ManagementCredentialHelper();
            managementCredentialHelper.Id = ID;
            managementCredentialHelper.Created = created;
            managementCredentialHelper.Modified = modified;
            return managementCredentialHelper;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property Username in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Username
        {
            get
            {
                return this._Username;
            }
            set
            {
                this.OnUsernameChanging(value);
                this._Username = value;
                this.OnUsernameChanged();
                this.OnPropertyChanged("Username");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Username;
        partial void OnUsernameChanging(string value);
        partial void OnUsernameChanged();
        /// <summary>
        /// There are no comments for Property Password in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Password
        {
            get
            {
                return this._Password;
            }
            set
            {
                this.OnPasswordChanging(value);
                this._Password = value;
                this.OnPasswordChanged();
                this.OnPropertyChanged("Password");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Password;
        partial void OnPasswordChanging(string value);
        partial void OnPasswordChanged();
        /// <summary>
        /// There are no comments for Property Created in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime Created
        {
            get
            {
                return this._Created;
            }
            set
            {
                this.OnCreatedChanging(value);
                this._Created = value;
                this.OnCreatedChanged();
                this.OnPropertyChanged("Created");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _Created;
        partial void OnCreatedChanging(global::System.DateTime value);
        partial void OnCreatedChanged();
        /// <summary>
        /// There are no comments for Property CreatedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CreatedBy
        {
            get
            {
                return this._CreatedBy;
            }
            set
            {
                this.OnCreatedByChanging(value);
                this._CreatedBy = value;
                this.OnCreatedByChanged();
                this.OnPropertyChanged("CreatedBy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CreatedBy;
        partial void OnCreatedByChanging(string value);
        partial void OnCreatedByChanged();
        /// <summary>
        /// There are no comments for Property Modified in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime Modified
        {
            get
            {
                return this._Modified;
            }
            set
            {
                this.OnModifiedChanging(value);
                this._Modified = value;
                this.OnModifiedChanged();
                this.OnPropertyChanged("Modified");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _Modified;
        partial void OnModifiedChanging(global::System.DateTime value);
        partial void OnModifiedChanged();
        /// <summary>
        /// There are no comments for Property ModifiedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ModifiedBy
        {
            get
            {
                return this._ModifiedBy;
            }
            set
            {
                this.OnModifiedByChanging(value);
                this._ModifiedBy = value;
                this.OnModifiedByChanged();
                this.OnPropertyChanged("ModifiedBy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ModifiedBy;
        partial void OnModifiedByChanging(string value);
        partial void OnModifiedByChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for LightSwitchApplication.Models.DispatchHelper in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("DispatchHelpers")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class DispatchHelper : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new DispatchHelper object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="entity">Initial value of Entity.</param>
        /// <param name="entitySet">Initial value of EntitySet.</param>
        /// <param name="uri">Initial value of Uri.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static DispatchHelper CreateDispatchHelper(int ID, string entity, string entitySet, string uri)
        {
            DispatchHelper dispatchHelper = new DispatchHelper();
            dispatchHelper.Id = ID;
            dispatchHelper.Entity = entity;
            dispatchHelper.EntitySet = entitySet;
            dispatchHelper.Uri = uri;
            return dispatchHelper;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Status in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Status
        {
            get
            {
                return this._Status;
            }
            set
            {
                this.OnStatusChanging(value);
                this._Status = value;
                this.OnStatusChanged();
                this.OnPropertyChanged("Status");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Status;
        partial void OnStatusChanging(string value);
        partial void OnStatusChanged();
        /// <summary>
        /// There are no comments for Property Entity in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Entity
        {
            get
            {
                return this._Entity;
            }
            set
            {
                this.OnEntityChanging(value);
                this._Entity = value;
                this.OnEntityChanged();
                this.OnPropertyChanged("Entity");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Entity;
        partial void OnEntityChanging(string value);
        partial void OnEntityChanged();
        /// <summary>
        /// There are no comments for Property EntitySet in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string EntitySet
        {
            get
            {
                return this._EntitySet;
            }
            set
            {
                this.OnEntitySetChanging(value);
                this._EntitySet = value;
                this.OnEntitySetChanged();
                this.OnPropertyChanged("EntitySet");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _EntitySet;
        partial void OnEntitySetChanging(string value);
        partial void OnEntitySetChanged();
        /// <summary>
        /// There are no comments for Property Uri in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Uri
        {
            get
            {
                return this._Uri;
            }
            set
            {
                this.OnUriChanging(value);
                this._Uri = value;
                this.OnUriChanged();
                this.OnPropertyChanged("Uri");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Uri;
        partial void OnUriChanging(string value);
        partial void OnUriChanged();
        /// <summary>
        /// There are no comments for Property LockName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string LockName
        {
            get
            {
                return this._LockName;
            }
            set
            {
                this.OnLockNameChanging(value);
                this._LockName = value;
                this.OnLockNameChanged();
                this.OnPropertyChanged("LockName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _LockName;
        partial void OnLockNameChanging(string value);
        partial void OnLockNameChanged();
        /// <summary>
        /// There are no comments for Property ErrorId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ErrorId
        {
            get
            {
                return this._ErrorId;
            }
            set
            {
                this.OnErrorIdChanging(value);
                this._ErrorId = value;
                this.OnErrorIdChanged();
                this.OnPropertyChanged("ErrorId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ErrorId;
        partial void OnErrorIdChanging(string value);
        partial void OnErrorIdChanged();
        /// <summary>
        /// There are no comments for Property ErrorMessage in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ErrorMessage
        {
            get
            {
                return this._ErrorMessage;
            }
            set
            {
                this.OnErrorMessageChanging(value);
                this._ErrorMessage = value;
                this.OnErrorMessageChanged();
                this.OnPropertyChanged("ErrorMessage");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ErrorMessage;
        partial void OnErrorMessageChanging(string value);
        partial void OnErrorMessageChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
